Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StoreManagementSystem.Data;
using StoreManagementSystem.Models;
using StoreManagementSystem.ViewModels;

namespace StoreManagementSystem.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ShoppingCartController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AddToCart(int id)
        {
            //retrieve the product from the database
            var addedProduct = _db.Products.Single(product => product.Id == id);
            var cart = new ShoppingCart(_db, HttpContext);
            cart.AddToCart(addedProduct);

            //go back to the main store page for more shopping
            return RedirectToAction("Index", "User");
        }
        public IActionResult DisplayCart()
        {
            var cart = new ShoppingCart(_db, HttpContext);
            //Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            return View(viewModel);
        }
    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using StoreManagementSystem.Data;
using StoreManagementSystem.Models;

namespace StoreManagementSystem.Controllers
{
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;
        public UserController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index(string searchString)
        {
            IEnumerable<Product> products;
            if (!String.IsNullOrEmpty(searchString))
            {
                products = _db.Products.Where(s => s.ProductName.Contains(searchString));
            }
            else
            {
                products = _db.Products;
            }
                /*IEnumerable<Product> products = from m in _db.Products
                             select m;
                if (!String.IsNullOrEmpty(searchString))
                {
                    products = products.Where(s => s.ProductName.Contains(searchString));
                }*/
                /*IEnumerable<Product> products = _db.Products;*/
                return View(products);
        }
        public IActionResult CategoryDropdown()
        {
            List<Category> cat = new List<Category>();
            cat = _db.Categories.ToList();
            ViewBag.message = cat;
            return View(cat);
        }
        
    }
}

Views/User/Index.cshtml
@model IEnumerable<StoreManagementSystem.Models.Product>
@{
    ViewData["Title"] = "Home Page";
}
<section class="home-screen">
    <div class="container">
        <div class="row justify-content-center align-items-center text-center">
            <div class="col-lg-10">
                <partial name="_Search" />
            </div>
        </div>
        <div class="album py-5 bg-light">

            <div class="row">
                @foreach (var item in Model)
                {
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm">
                            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c" /><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
                            <div class="card-body">
                                <h5 class="card-title">@item.ProductName</h5>
                                <p class="card-text">$@item.ProductUnitPrice</p>
                                <p class="card-text">@item.ProductDescription</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a class="btn btn-sm btn-outline-success" asp-controller="ShoppingCart" asp-action="AddToCart" asp-route-Id="@item.Id"><i class="fa fa-shopping-cart"></i>Add to Cart</a>
                                        <a asp-controller="Product" asp-action="SingleProduct" asp-route-Id="@item.Id" class="btn btn-sm btn-outline-secondary">View</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }


            </div>
        </div>
    </div>
    
</section>