Models/ShoppingCart.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using StoreManagementSystem.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace StoreManagementSystem.Models
{
    public class ShoppingCart
    {
        private readonly ApplicationDbContext _db;
        public ShoppingCart(ApplicationDbContext db, HttpContext context)
        {
            _db = db;
            ShoppingCartId = GetCartId(context);
        }

        
        private string ShoppingCartId { get; set; }
        public const string CartSessionKey = "Id";
       
        //Helper method to simplify shopping cart calls

        public void AddToCart(Product product)
        {
            //get the matching cart
            var cartItem = _db.Carts.SingleOrDefault(c => c.Id == ShoppingCartId && c.ProductId == product.Id);
            if (cartItem == null)
            {
                
                //create a new cart item if no cart exists
                cartItem = new Cart
                {
                    ProductId = product.Id,
                    Id = ShoppingCartId,
                    Quantity = 1,
                    DateCreated = DateTime.Now
                };
                _db.Carts.Add(cartItem);
            }
            else
            {
                //if the item does exist in thecart, then add one to the quantity
                cartItem.Quantity++;
            }
            //save changes
            _db.SaveChanges();
        }

        public int RemoveFromCart(int id)
        {
            //get the cart
            var cartItem = _db.Carts.Single(cart => cart.Id == ShoppingCartId && cart.RecordId == id);
            int itemCount = 0;
            if (cartItem != null)
            {
                if (cartItem.Quantity > 1)
                {
                    cartItem.Quantity--;
                    itemCount = cartItem.Quantity;
                }
                else
                {
                    _db.Carts.Remove(cartItem);
                }
                //save changes
                _db.SaveChanges();
            }
            return itemCount;
        }
        public void EmptyCart()
        {
            var cartItems = _db.Carts.Where(cart => cart.Id == ShoppingCartId);
            foreach (var item in cartItems)
            {
                _db.Carts.Remove(item);
            }
            //savechanges
            _db.SaveChanges();
        }
        public List<Cart> GetCartItems()
        {
            return _db.Carts.Where(cart => cart.Id == ShoppingCartId).ToList();
        }
        public int GetCount()
        {
            //get the count of each item in the cart and sum them up
            int? count = (from cartItems in _db.Carts
                          where cartItems.Id == ShoppingCartId
                          select (int?)cartItems.Quantity).Sum();
            //return 0 if all enteries are null
            return count ?? 0;
        }
        public double GetTotal()
        {
            //multiply product price by count of that product to get the current price for each of those products in the cart
            //sum all album price totaals to get the cart total
            double? total = (from cartItems in _db.Carts
                              where cartItems.Id == ShoppingCartId
                              select (int?)cartItems.Quantity * cartItems.Product.ProductUnitPrice).Sum();
            return total ?? 0.0;
        }
        public int CreateOrder(Order order)
        {
            double orderTotal = 0;
            var cartItems = GetCartItems();
            //iterate over the items in the cart, adding the order details for each
            foreach (var item in cartItems)
            {
                var orderDetail = new OrderDetail
                {
                    ProductID = item.ProductId,
                    OrderId = order.OrderId,
                    UnitPrice = item.Product.ProductUnitPrice,
                    Quantity = item.Quantity,
                };

                //set the order total of the shopping cart
                orderTotal += (item.Quantity * item.Product.ProductUnitPrice);
                _db.OrderDetails.Add(orderDetail);
            }
            //set the order's total to the orderTotal count
            order.Total = orderTotal;
            //save the order
            _db.SaveChanges();
            //empty the shopping cart
            EmptyCart();
            //return the OrderId as the confirmation number
            return order.OrderId;
        }

        //we are using HttpContext to allow access to cookies
        public string GetCartId(HttpContext context)
        {
            if (context.Session.GetString(CartSessionKey) == null)
            {
                if (!string.IsNullOrWhiteSpace(context.User.Identity.Name))
                {
                    context.Session.SetString(CartSessionKey, context.User.Identity.Name);
                }
                else
                {
                    //generate a new random GUID using System.Guid class
                    Guid tempCartId = Guid.NewGuid();
                    //send tempCartId back to client as a cookie
                    context.Session.SetString(CartSessionKey, tempCartId.ToString());
                }
            }
            return context.Session.GetString(CartSessionKey);
        }
        //when a user has logged in, migrate their shopping cart to be associated with their username
        public void MigrateCart(string userName)
        {
            var shoppingCart = _db.Carts.Where(c => c.Id == ShoppingCartId);
            foreach (Cart item in shoppingCart)
            {
                item.Id = userName;
            }
            _db.SaveChanges();
        }
    }
}

ViewModels/ShoppingCartViewModel.cs
using StoreManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StoreManagementSystem.ViewModels
{
    public class ShoppingCartViewModel
    {
        public List<Cart> CartItems { get; set; }
        public double CartTotal { get; set; }
    }
}

Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StoreManagementSystem.Data;

namespace StoreManagementSystem.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly UserManager<MyIdentityUser> userManager;
        public CheckoutController(UserManager<MyIdentityUser> userManager)
        {
            this.userManager = userManager;
        }
        [AllowAnonymous]
        public IActionResult Index()
        {
            //MyIdentityUser user = userManager.GetUserAsync(HttpContext.User).Result;
            //ViewBag.Message = $"Welcome {user.Email}";
            //if(userManager.IsInRoleAsync(user, "Customer").Result)
            //{
            //    ViewBag.RoleMessage = "You are a Customer User";
            //}
            return View();
        }
    }
}

Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StoreManagementSystem.Data;
using StoreManagementSystem.Models;
using StoreManagementSystem.ViewModels;

namespace StoreManagementSystem.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ShoppingCartController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AddToCart(int id)
        {
            //retrieve the product from the database
            var addedProduct = _db.Products.Single(product => product.Id == id);
            var cart = new ShoppingCart(_db, HttpContext);
            cart.AddToCart(addedProduct);

            //go back to the main store page for more shopping
            return RedirectToAction("Index", "User");
        }
        public IActionResult DisplayCart()
        {
            var cart = new ShoppingCart(_db, HttpContext);
            //Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            return View(viewModel);
        }
    }
}

Views/ShoppingCart/DisplayCart.cshtml
@model StoreManagementSystem.ViewModels.ShoppingCartViewModel
@{
    ViewData["Title"] = "DisplayCart";
}

<section class="display-cart">
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-lg-8">

                <!-- Card -->
                <div class="card wish-list mb-3">
                    <div class="card-body">
                        <h5 class="mb-4">Cart (<span>2</span> items)</h5>
                        @foreach (var item in Model.CartItems)
                        {

                            <div class="row mb-4">
                                <div class="col-md-5 col-lg-3 col-xl-3">
                                    <div class="view zoom overlay z-depth-1 rounded mb-3 mb-md-0">
                                        <a href="#!">
                                            <div class="mask waves-effect waves-light">
                                                <img class="img-fluid w-100"
                                                     src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg">
                                                <div class="mask rgba-black-slight waves-effect waves-light"></div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-md-7 col-lg-9 col-xl-9">
                                    <div>
                                        <div class="d-flex justify-content-between">
                                            <div>
                                                <h5>@item.ProductId</h5>
                                                <p class="mb-3 text-muted text-uppercase small">Shirt - blue</p>
                                                <p class="mb-2 text-muted text-uppercase small">Color: blue</p>
                                                <p class="mb-3 text-muted text-uppercase small">Size: M</p>
                                            </div>
                                            <div>
                                                <div class="def-number-input number-input safari_only mb-0 w-100">

                                                    <input class="quantity" min="0" name="quantity" value=@item.Quantity type="number">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="d-flex justify-content-between align-items-center">
                                            <div>
                                                <a asp-controller="" asp-action="" asp-route-Id="@item.ProductId" class="card-link-secondary small text-uppercase mr-3">
                                                    <i class="fas fa-trash-alt mr-1"></i> Remove item
                                                </a>
                                                <a href="#!" type="button" class="card-link-secondary small text-uppercase">
                                                    <i class="fas fa-heart mr-1"></i> Move to wish list
                                                </a>
                                            </div>
                                            <p class="mb-0"><span><strong>$17.99</strong></span></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }


                        <hr class="mb-4">
                        <p class="text-primary mb-0">
                            <i class="fas fa-info-circle mr-1"></i> Do not delay the purchase, adding
                            items to your cart does not mean booking them.
                        </p>

                    </div>
                </div>
                <!-- Card -->
            </div>
            <div class="col-lg-4">

                <!-- Card -->
                <div class="card mb-3">
                    <div class="card-body">

                        <h5 class="mb-3">The total amount of</h5>

                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
                                Temporary amount
                                <span>
                                    @{
                                        @Model.CartTotal.ToString("C");
                                    }
                                </span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                                Shipping
                                <span>Gratis</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                                <div>
                                    <strong>The total amount of</strong>
                                    <strong class="mb-0">
                                        (including VAT)
                                    </strong>
                                </div>
                                <span>
                                    <strong>
                                        @{
                                            @Model.CartTotal.ToString("C");
                                        }
                                    </strong>
                                </span>
                            </li>
                        </ul>

                        <a class="btn btn-primary btn-block waves-effect waves-light" asp-controller="Checkout" asp-action="Index">Go to Checkout</a>

                    </div>
                </div>
                <!-- Card -->

            </div>
        </div>
    </div>
</section>